// angular/crud/frontend/src/app/views/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { HeaderService } from 'src/app/components/template/header/header.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  // Aula 466. Atualizando os Títulos
  constructor(private headerService: HeaderService) { 
    headerService.headerData = {
      title: 'Início',
      icon: 'home',
      routeUrl: ''
    }
  }

  ngOnInit(): void {
  }

}

<!-- Aula 441. Componente Início (Home) -->
<mat-card class="home mat-elevation-z3">
    <mat-card-title class="title">
        Bem Vindo!
    </mat-card-title>
    <mat-card-subtitle class="subtitle">
        Sistema para exemplificar a construção de um cadastro em Angular
    </mat-card-subtitle>
    <!-- Aula 444. Diretivas na Prática #02 
    Este exemplo é apenas p/ explicar o uso. Não tem aplicabilidade no projeto -->
    <!-- <ul>
        <li *appFor="let n in [1, 2, 3]">{{ n }}</li>
    </ul> -->
</mat-card>

// react/crud/frontend/src/components/home/Home.jsx
// Aula 383. Componente Conteúdo
import React from 'react'
import Main from '../template/Main'

export default props => 
    <Main icon="home" title="Início"
        subtitle="Segundo Projeto do capítulo de react.">
        {/* Aula 383. Componente Conteúdo */}
        <div className="display4">Bem Vindo!</div>
        <hr />
        <p className="mb-0">
            Sistema para exemplificar a construção de um cadastro desenvolvido em React!
        </p>
    </Main>
